spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Atiye_2976
  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 5min
    refreshTokenExpiration: 604800
stripe:
  secretkey: ${STRIPE_SECRET_KEY}
websiteUrl: http://localhost:4242
